name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: deploy
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd /var/www/laratechlabs.com/laratechlabs
          git pull origin main
          npm install
          npm run build
          sudo systemctl reload nginx
