name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
        
    - name: Get runner IP and add to security group
      id: ip
      run: |
        RUNNER_IP=$(curl -s https://checkip.amazonaws.com)
        echo "🔍 Runner IP: $RUNNER_IP"
        echo "runner_ip=$RUNNER_IP" >> $GITHUB_OUTPUT
        
        echo "📝 Adding IP to security group..."
        aws ec2 authorize-security-group-ingress \
          --group-id ${{ secrets.SECURITY_GROUP_ID }} \
          --protocol tcp \
          --port 22 \
          --cidr ${RUNNER_IP}/32 \
          && echo "✅ Successfully added IP to security group" \
          || echo "❌ Failed to add IP to security group"
          
    - name: Wait for security group rule to propagate
      run: |
        echo "⏳ Waiting 30 seconds for rule to propagate..."
        sleep 30
        echo "✅ Wait complete"
        
    - name: Test connection before SSH
      run: |
        echo "🧪 Testing connection to ${{ secrets.HOST }}:22..."
        timeout 10 bash -c "</dev/tcp/${{ secrets.HOST }}/22" && echo "✅ Port 22 is reachable" || echo "❌ Port 22 is not reachable"
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: deploy
        key: ${{ secrets.PRIVATE_KEY }}
        timeout: 60s
        command_timeout: 300s
        script: |
          cd /var/www/laratechlabs.com/laratechlabs
          git pull origin main
          npm install
          npm run build
          sudo systemctl reload nginx
          echo "✅ Deployment completed successfully!"
          
    - name: Remove runner IP from security group
      if: always()
      run: |
        echo "🧹 Cleaning up security group rule..."
        aws ec2 revoke-security-group-ingress \
          --group-id ${{ secrets.SECURITY_GROUP_ID }} \
          --protocol tcp \
          --port 22 \
          --cidr ${{ steps.ip.outputs.runner_ip }}/32 \
          && echo "✅ Successfully removed IP from security group" \
          || echo "⚠️ Could not remove IP (may have been removed already)"
